### ISSUE TITLE
1 out of N runs starts successfully, others fail immediately

### ISSUE THREAD

**Issue by eldarkurtic** [mosaicml/examples#292]
Hi,
I am trying to reproduce BERT pretraining example by following the steps here: https://github.com/mosaicml/examples/tree/main/examples/bert without any custom modifications. 
I am trying to run it on 4xA100 80GB, inside a conda environment. A really weird and annoying problem I am facing now is that only 1 lucky run out of N attempts to start succeeds to start with training. All other (N-1) attempts fail with this error:

```shell
Training using config:
data_local: /ssdpool/eldar/bert_c4
data_remote: null
max_seq_len: 128
tokenizer_name: bert-base-uncased
mlm_probability: 0.15
run_name: hf-bert-base-uncased
model:
  name: hf_bert
  use_pretrained: false
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  model_config:
    num_attention_heads: 12
    num_hidden_layers: 12
    max_position_embedding: 512
    attention_probs_dropout_prob: 0.1
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
  drop_last: true
  num_workers: 8
eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
    mlm_probability: 0.15
  drop_last: false
  num_workers: 8
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur
  alpha_f: 0.02
optimizer:
  name: decoupled_adamw
  lr: 0.0005
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-05
max_duration: 286720000sp
eval_interval: 2000ba
global_train_batch_size: 4096
seed: 17
device_eval_batch_size: 128
device_train_microbatch_size: 128
precision: bf16
progress_bar: false
log_to_console: true
console_log_interval: 1ba
callbacks:
  speed_monitor:
    window_size: 500
  lr_monitor: {}

Initializing model...
n_params=1.0951e+08
Building train loader...
Building eval loader...

ERROR:composer.cli.launcher:Rank 1 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/multiprocessing/resource_tracker.py:229: UserWarning: resource_tracker: '/eb22f1_next_epoch': [Errno 2] No such file or directory: '/eb22f1_next_epoch'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/multiprocessing/resource_tracker.py:229: UserWarning: resource_tracker: '/d016e8_next_epoch': [Errno 2] No such file or directory: '/d016e8_next_epoch'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/multiprocessing/resource_tracker.py:229: UserWarning: resource_tracker: '/eb22f1_barrier': [Errno 2] No such file or directory: '/eb22f1_barrier'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/multiprocessing/resource_tracker.py:229: UserWarning: resource_tracker: '/d016e8_barrier': [Errno 2] No such file or directory: '/d016e8_barrier'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/multiprocessing/resource_tracker.py:229: UserWarning: resource_tracker: '/d016e8_shard_states': [Errno 2] No such file or directory: '/d016e8_shard_states'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/multiprocessing/resource_tracker.py:229: UserWarning: resource_tracker: '/eb22f1_shard_states': [Errno 2] No such file or directory: '/eb22f1_shard_states'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
Global rank 1 (PID 4033709) exited with code 1
----------Begin global rank 1 STDOUT----------
Training using config:
data_local: /ssdpool/eldar/bert_c4
data_remote: null
max_seq_len: 128
tokenizer_name: bert-base-uncased
mlm_probability: 0.15
run_name: hf-bert-base-uncased
model:
  name: hf_bert
  use_pretrained: false
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  model_config:
    num_attention_heads: 12
    num_hidden_layers: 12
    max_position_embedding: 512
    attention_probs_dropout_prob: 0.1
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
  drop_last: true
  num_workers: 8
eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
    mlm_probability: 0.15
  drop_last: false
  num_workers: 8
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur
  alpha_f: 0.02
optimizer:
  name: decoupled_adamw
  lr: 0.0005
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-05
max_duration: 286720000sp
eval_interval: 2000ba
global_train_batch_size: 4096
seed: 17
device_eval_batch_size: 128
device_train_microbatch_size: 512
precision: bf16
progress_bar: false
log_to_console: true
console_log_interval: 1ba
callbacks:
  speed_monitor:
    window_size: 500
  lr_monitor: {}

Initializing model...
n_params=1.0951e+08
Building train loader...
Building eval loader...

----------End global rank 1 STDOUT----------
----------Begin global rank 1 STDERR----------
Traceback (most recent call last):
  File "/home/ekurtic/github/eldarkurtic/mosaicml/examples/examples/bert/main.py", line 141, in <module>
    main(cfg)
  File "/home/ekurtic/github/eldarkurtic/mosaicml/examples/examples/bert/main.py", line 91, in main
    trainer = Trainer(
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/composer/trainer/trainer.py", line 975, in __init__
    dist.initialize_dist(device, dist_timeout)
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/composer/utils/dist.py", line 426, in initialize_dist
    dist.init_process_group(device_obj.dist_backend, timeout=timeout_timedelta)
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 761, in init_process_group
    default_pg = _new_process_group_helper(
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 909, in _new_process_group_helper
    pg = _create_process_group_wrapper(
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/torch/distributed/distributed_c10d.py", line 3232, in _create_process_group_wrapper
    helper_pg = ProcessGroupGloo(store, rank, world_size, timeout=timeout)
RuntimeError: [../third_party/gloo/gloo/transport/tcp/pair.cc:799] connect [10.36.193.84]:1927: Connection refused
Exception ignored in: <function StreamingDataset.__del__ at 0x1482b4fc11f0>
Traceback (most recent call last):
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/streaming/base/dataset.py", line 851, in __del__
    wait_for_local_leader(world)
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/streaming/base/util.py", line 62, in wait_for_local_leader
    wait_for_file_to_exist(dir_path,
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/streaming/base/util.py", line 49, in wait_for_file_to_exist
    raise RuntimeError(f'{err_msg}, bailing out: ' + f'{timeout:.3f} < {dt:.3f} sec.')
RuntimeError: Waiting for local rank 0, bailing out: 60.000 < 60.033 sec.
Exception ignored in: <function StreamingDataset.__del__ at 0x1482b4fc11f0>
Traceback (most recent call last):
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/streaming/base/dataset.py", line 851, in __del__
    wait_for_local_leader(world)
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/streaming/base/util.py", line 62, in wait_for_local_leader
    wait_for_file_to_exist(dir_path,
  File "/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/site-packages/streaming/base/util.py", line 49, in wait_for_file_to_exist
    raise RuntimeError(f'{err_msg}, bailing out: ' + f'{timeout:.3f} < {dt:.3f} sec.')
RuntimeError: Waiting for local rank 0, bailing out: 60.000 < 60.034 sec.
/home/ekurtic/miniconda3/envs/mosaicml/lib/python3.9/multiprocessing/resource_tracker.py:216: UserWarning: resource_tracker: There appear to be 6 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

----------End global rank 1 STDERR----------
ERROR:composer.cli.launcher:Global rank 0 (PID 4033708) exited with code -15
```

And the bash script I am using to run this:
```shell
export HF_DATASETS_CACHE=/ssdpool/eldar/hf_cache
export CUDA_VISIBLE_DEVICES=4,5,6,7
export MASTER_PORT=12345
export WORLD_SIZE=4
export TORCH_DISTRIBUTED_DEBUG=DETAIL

composer main.py yamls/main/hf-bert-base-uncased.yaml
```

What am I doing wrong here, any ideas? Why is GLOO complaining in error messages above, shouldn't we use NCCL as a backend for DDP runs?

**Comment by dakinggg** [comment]
First thing to check is probably that your GPU environment is working. If `device` is not provided, `Trainer` will automatically select gpu or cpu based on `torch.cuda.is_available()` (https://github.com/mosaicml/composer/blob/12b94d94696180dd1df2ba536fc2dab588b17786/composer/utils/device.py#L30-L31). The other thing I notice is that your rank 0 and rank 1 logs are printing a different value for `device_train_microbatch_size`, which is pretty weird, since the config you reference has that set to 128 (https://github.com/mosaicml/examples/blob/dd67dee70fc5cd1b69167a15a9ca819dd7cce28b/examples/bert/yamls/main/hf-bert-base-uncased.yaml#L80).

**Comment by eldarkurtic** [comment]
@dakinggg do you have any suggestions how to test if my "GPU environment is working"? 

Btw, what is the correct way to run DDP experiments with composer library: `composer main.py` or `composer -n 8 main.py`?

**Comment by dakinggg** [comment]
you can just run `python -c "import torch; print(torch.cuda.is_available(), torch.cuda.device_count())`, which should print out `True, N_GPUS` if everything is set up correctly.

Running `composer main.py` will use all available gpus (gets defaults from `LOCAL_WORLD_SIZE` or `torch.cuda.device_count()` see https://github.com/mosaicml/composer/blob/20fb86b476d91749528a989265c3e211eb1d774d/composer/cli/launcher.py#L140-L151). whereas `composer -n 8 main.py` will explicitly launch 8 processes. Either should be fine.

You can also try adding `device: gpu` to the yaml you are running to explicitly tell composer to use gpu. That should error if something is set up incorrectly.

**Comment by eldarkurtic** [comment]
I finally got some time to debug, and it turns out the process just hangs at this specific line: `dist.init_process_group(device_obj.dist_backend, timeout=timeout_timedelta)` (https://github.com/mosaicml/composer/blob/38cec0937640ccee148ca4f6611f94e40e35ad22/composer/utils/dist.py#L426), and breaks with: `RuntimeError: Waiting for local rank 0, bailing out: 60.000 < 60.033 sec.`. I have played with different values for `timeout_timedelta` but no difference. A very interesting thing is that the only way that I am able to run the experiment is like this:
```shell
while true
do
    composer -n 8 main.py yamls/main/hf-bert-base-uncased.yaml
done
```
and after a number of attempts, it would somehow magically succeed  with distributed initialization...

The server and environment where I am running this seem to be fine, I have tried to run DDP experiments with two different repositories (FFCV and HF-transformers) and both of them work just fine, `dist.init_process_group(...)` never hangs. However, I have noticed one difference between mosaicml and the other two repos that run successfully: in the "main" python script, they both spawn distributed training with `torch.multiprocessing.spawn(...)`, and I am not able to find any instances of similar command when searching through the mosaicml codebase. Am I missing something here?

**Comment by dakinggg** [comment]
Could you share the output of `pip list`? And also share the full trace and the full script you are running? The `RuntimeError: Waiting for local rank 0, bailing out: 60.000 < 60.033 sec.` error is just coming when our streaming dataset tries to clean up, and is not the cause of the issue.

**Comment by dakinggg** [comment]
Could you also pass `python_log_level='debug'` to trainer? It will print out the distributed environment that it is trying to initialize.

**Comment by eldarkurtic** [comment]
`pip list` output:
```
Package                Version           Editable project location
---------------------- ----------------- ---------------------------------------------------------------------
aiohttp                3.8.4
aiosignal              1.3.1
antlr4-python3-runtime 4.9.3
async-timeout          4.0.2
attrs                  22.2.0
bcrypt                 4.0.1
boto3                  1.26.113
botocore               1.29.113
Brotli                 1.0.9
brotlipy               0.7.0
certifi                2022.12.7
cffi                   1.15.1
cfgv                   3.3.1
chardet                5.1.0
charset-normalizer     2.0.4
circuitbreaker         1.4.0
click                  8.1.3
cmake                  3.26.3
contourpy              1.0.7
coolname               2.2.0
coverage               7.2.3
cryptography           39.0.2
cycler                 0.11.0
datasets               2.10.1
dill                   0.3.6
distlib                0.3.6
docker-pycreds         0.4.0
einops                 0.5.0
exceptiongroup         1.1.1
filelock               3.11.0
flit_core              3.8.0
fonttools              4.39.3
frozenlist             1.3.3
fsspec                 2023.4.0
gitdb                  4.0.10
GitPython              3.1.31
huggingface-hub        0.13.4
identify               2.5.22
idna                   3.4
importlib-metadata     6.3.0
iniconfig              2.0.0
jmespath               1.0.1
kiwisolver             1.4.4
matplotlib             3.7.1
mkl-fft                1.3.1
mkl-random             1.2.2
mkl-service            2.4.0
mosaicml               0.13.2
mosaicml-examples      0.0.3             
mosaicml-streaming     0.3.0
multidict              6.0.4
multiprocess           0.70.14
nodeenv                1.7.0
numpy                  1.23.5
oci                    2.98.0
omegaconf              2.2.3
packaging              22.0
pandas                 2.0.0
paramiko               3.1.0
pathtools              0.1.2
Pillow                 9.5.0
pip                    23.0.1
platformdirs           3.2.0
pluggy                 1.0.0
pre-commit             2.21.0
promise                2.3
protobuf               4.22.3
psutil                 5.9.4
py-cpuinfo             9.0.0
pyarrow                11.0.0
pycparser              2.21
PyNaCl                 1.5.0
pynvml                 11.5.0
pyOpenSSL              23.1.1
pyparsing              3.0.9
pyright                1.1.296
PySocks                1.7.1
pytest                 7.3.0
pytest_codeblocks      0.16.1
pytest-cov             4.0.0
python-dateutil        2.8.2
python-snappy          0.6.1
pytorch-ranger         0.1.1
pytz                   2023.3
PyYAML                 6.0
regex                  2023.3.23
requests               2.28.1
responses              0.18.0
s3transfer             0.6.0
sentry-sdk             1.19.1
setproctitle           1.3.2
setuptools             65.6.3
shortuuid              1.0.11
six                    1.16.0
slack-sdk              3.21.1
smmap                  5.0.0
tabulate               0.9.0
tokenizers             0.13.3
toml                   0.10.2
tomli                  2.0.1
torch                  1.12.1
torch-optimizer        0.3.0
torchaudio             0.12.1
torchmetrics           0.11.3
torchvision            0.13.1
tqdm                   4.65.0
transformers           4.25.1
triton                 2.0.0.dev20221103
typing_extensions      4.4.0
tzdata                 2023.3
urllib3                1.26.15
virtualenv             20.21.0
wandb                  0.13.6
wheel                  0.38.4
xxhash                 3.2.0
yarl                   1.8.2
zipp                   3.15.0
zstd                   1.5.5.1
```

I am literally trying to reproduce training of the HF-BERT from scratch by following the steps here: [https://github.com/mosaicml/examples/tree/main/examples/bert](https://github.com/mosaicml/examples/tree/main/examples/bert). No changes to the code, just running `composer -n main.py yamls/main/hf-bert-base-uncased.yaml`.

The full trace is here with `python_log_level='debug'`:
```
Training using config:
data_local: ./mosaicml_c4_bert
data_remote: null
max_seq_len: 128
tokenizer_name: bert-base-uncased
mlm_probability: 0.15
run_name: debug
model:
  name: hf_bert
  use_pretrained: false
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  model_config:
    num_attention_heads: 12
    num_hidden_layers: 12
    max_position_embedding: 512
    attention_probs_dropout_prob: 0.1
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
  drop_last: true
  num_workers: 8
eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
    mlm_probability: 0.15
  drop_last: false
  num_workers: 8
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur
  alpha_f: 0.02
optimizer:
  name: decoupled_adamw
  lr: 0.0005
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-05
max_duration: 1ep
eval_interval: 2000ba
global_train_batch_size: 4096
seed: 17
device_eval_batch_size: 128
device_train_microbatch_size: 512
precision: bf16
device: gpu
progress_bar: true
log_to_console: true
console_log_interval: 1ba
callbacks:
  speed_monitor:
    window_size: 500
  lr_monitor: {}
loggers:
  wandb:
    project: mosaicml_bert_pretraining
    entity: ek

Initializing model...
n_params=1.0951e+08
Building train loader...
Building eval loader...
2023-04-24 16:03:12,379: rank0[1003409][MainThread]: DEBUG: composer.utils.dist: Initializing torch.dist: global_rank=0, local_rank=0, world_size=8, local_world_size=8, node_rank=0
ERROR:composer.cli.launcher:Rank 1 crashed with exit code 1.
Waiting up to 30 seconds for all training processes to terminate. Press Ctrl-C to exit immediately.
/home/ek/miniconda3/envs/mosaicml/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
/home/ek/miniconda3/envs/mosaicml/lib/python3.10/multiprocessing/resource_tracker.py:237: UserWarning: resource_tracker: '/af0626_barrier': [Errno 2] No such file or directory: '/af0626_barrier'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ek/miniconda3/envs/mosaicml/lib/python3.10/multiprocessing/resource_tracker.py:237: UserWarning: resource_tracker: '/e9c924_next_epoch': [Errno 2] No such file or directory: '/e9c924_next_epoch'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ek/miniconda3/envs/mosaicml/lib/python3.10/multiprocessing/resource_tracker.py:237: UserWarning: resource_tracker: '/e9c924_shard_states': [Errno 2] No such file or directory: '/e9c924_shard_states'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ek/miniconda3/envs/mosaicml/lib/python3.10/multiprocessing/resource_tracker.py:237: UserWarning: resource_tracker: '/af0626_shard_states': [Errno 2] No such file or directory: '/af0626_shard_states'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ek/miniconda3/envs/mosaicml/lib/python3.10/multiprocessing/resource_tracker.py:237: UserWarning: resource_tracker: '/af0626_next_epoch': [Errno 2] No such file or directory: '/af0626_next_epoch'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
/home/ek/miniconda3/envs/mosaicml/lib/python3.10/multiprocessing/resource_tracker.py:237: UserWarning: resource_tracker: '/e9c924_barrier': [Errno 2] No such file or directory: '/e9c924_barrier'
  warnings.warn('resource_tracker: %r: %s' % (name, e))
Global rank 1 (PID 1003410) exited with code 1
----------Begin global rank 1 STDOUT----------
Training using config:
data_local: ./mosaicml_c4_bert
data_remote: null
max_seq_len: 128
tokenizer_name: bert-base-uncased
mlm_probability: 0.15
run_name: debug
model:
  name: hf_bert
  use_pretrained: false
  pretrained_model_name: ${tokenizer_name}
  tokenizer_name: ${tokenizer_name}
  model_config:
    num_attention_heads: 12
    num_hidden_layers: 12
    max_position_embedding: 512
    attention_probs_dropout_prob: 0.1
train_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: train
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: true
    mlm_probability: ${mlm_probability}
  drop_last: true
  num_workers: 8
eval_loader:
  name: text
  dataset:
    local: ${data_local}
    remote: ${data_remote}
    split: val
    tokenizer_name: ${tokenizer_name}
    max_seq_len: ${max_seq_len}
    shuffle: false
    mlm_probability: 0.15
  drop_last: false
  num_workers: 8
scheduler:
  name: linear_decay_with_warmup
  t_warmup: 0.06dur
  alpha_f: 0.02
optimizer:
  name: decoupled_adamw
  lr: 0.0005
  betas:
  - 0.9
  - 0.98
  eps: 1.0e-06
  weight_decay: 1.0e-05
max_duration: 1ep
eval_interval: 2000ba
global_train_batch_size: 4096
seed: 17
device_eval_batch_size: 128
device_train_microbatch_size: 512
precision: bf16
device: gpu
progress_bar: true
log_to_console: true
console_log_interval: 1ba
callbacks:
  speed_monitor:
    window_size: 500
  lr_monitor: {}
loggers:
  wandb:
    project: mosaicml_bert_pretraining
    entity: ek

Initializing model...
n_params=1.0951e+08
Building train loader...
Building eval loader...

----------End global rank 1 STDOUT----------
----------Begin global rank 1 STDERR----------
2023-04-24 16:03:12,065: rank1[1003410][MainThread]: DEBUG: composer.utils.dist: Initializing torch.dist: global_rank=1, local_rank=1, world_size=8, local_world_size=8, node_rank=0
Traceback (most recent call last):
  File "/home/ek/github/eldarkurtic/mosaicml/examples/examples/bert/acdc_main.py", line 459, in <module>
    main(cfg)
  File "/home/ek/github/eldarkurtic/mosaicml/examples/examples/bert/acdc_main.py", line 405, in main
    trainer = Trainer(
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/composer/trainer/trainer.py", line 975, in __init__
    dist.initialize_dist(device, dist_timeout)
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/composer/utils/dist.py", line 427, in initialize_dist
    dist.init_process_group(device_obj.dist_backend, timeout=timeout_timedelta)
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 627, in init_process_group
    _store_based_barrier(rank, store, timeout)
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 242, in _store_based_barrier
    worker_count = store.add(store_key, 0)
RuntimeError: Broken pipe
Exception ignored in: <function StreamingDataset.__del__ at 0x14c8a55131c0>
Traceback (most recent call last):
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/streaming/base/dataset.py", line 851, in __del__
    wait_for_local_leader(world)
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/streaming/base/util.py", line 62, in wait_for_local_leader
    wait_for_file_to_exist(dir_path,
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/streaming/base/util.py", line 49, in wait_for_file_to_exist
    raise RuntimeError(f'{err_msg}, bailing out: ' + f'{timeout:.3f} < {dt:.3f} sec.')
RuntimeError: Waiting for local rank 0, bailing out: 60.000 < 60.053 sec.
Exception ignored in: <function StreamingDataset.__del__ at 0x14c8a55131c0>
Traceback (most recent call last):
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/streaming/base/dataset.py", line 851, in __del__
    wait_for_local_leader(world)
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/streaming/base/util.py", line 62, in wait_for_local_leader
    wait_for_file_to_exist(dir_path,
  File "/home/ek/miniconda3/envs/mosaicml/lib/python3.10/site-packages/streaming/base/util.py", line 49, in wait_for_file_to_exist
    raise RuntimeError(f'{err_msg}, bailing out: ' + f'{timeout:.3f} < {dt:.3f} sec.')
RuntimeError: Waiting for local rank 0, bailing out: 60.000 < 60.055 sec.
/home/ek/miniconda3/envs/mosaicml/lib/python3.10/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 6 leaked shared_memory objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '

----------End global rank 1 STDERR----------
ERROR:composer.cli.launcher:Global rank 0 (PID 1003409) exited with code -15
```

**Comment by dakinggg** [comment]
Could you try running a script that just calls `dist.initialize_dist(device, dist_timeout)`?

**Comment by dakinggg** [comment]
Closing due to inactivity.
