### ISSUE TITLE
Error using PIL

### ISSUE THREAD

**Issue by FinTexIFB** [mosaicml/examples#358]
Hi!

I try to train my own BERT model using your code. First of all, I tried to test the setup with your default configuration using the C4 dataset.

I get an error when I try to run the following command for testing pre-training on the Huggingface model:
`composer main.py yamls/test/main.yaml`

The error message is as follows:
**ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)**

I tried to update pip, uninstall and reinstall pillow. However, this did not help. I followed all the steps that you mentioned before the pre-training command. I use a 8xA100 80GB node.

I would appreciate any hints that might help! :)

**Comment by mvpatel2000** [comment]
We provide a set of docker images [here](https://github.com/mosaicml/composer/tree/dev/docker) which may be useful for you. It typically helps standardize this process and avoid install issues.

Would you mind providing a full trace? Can you also describe what exactly you did to set things up via pip? happy to check if there is an issue on our end in terms of requirements

**Comment by FinTexIFB** [comment]
Thank you very much for the quick response! I tried one of the other docker images (mosaicml/composer:latest), but unfortunately I got another error message in the pre-training testing step. This time, there is a problem with the sentence-piece package. 

Here is the full trace:
`Traceback (most recent call last):
  File "/dss/dsshome1/0A/ru56sax2/.local/bin/composer", line 5, in <module>
    from composer.cli.launcher import main
  File "/dss/dsshome1/0A/ru56sax2/.local/lib/python3.8/site-packages/composer/__init__.py", line 7, in <module>
    from composer.core import Algorithm, Callback, DataSpec, Engine, Evaluator, Event, State, Time, Timestamp, TimeUnit
  File "/dss/dsshome1/0A/ru56sax2/.local/lib/python3.8/site-packages/composer/core/__init__.py", line 14, in <module>
    from composer.core.engine import Engine, Trace
  File "/dss/dsshome1/0A/ru56sax2/.local/lib/python3.8/site-packages/composer/core/engine.py", line 85, in <module>
    from composer.loggers import Logger, LoggerDestination
  File "/dss/dsshome1/0A/ru56sax2/.local/lib/python3.8/site-packages/composer/loggers/__init__.py", line 15, in <module>
    from composer.loggers.cometml_logger import CometMLLogger
  File "/dss/dsshome1/0A/ru56sax2/.local/lib/python3.8/site-packages/composer/loggers/cometml_logger.py", line 14, in <module>
    from torchvision.utils import draw_segmentation_masks
  File "/dss/dsshome1/0A/ru56sax2/.local/lib/python3.8/site-packages/torchvision/__init__.py", line 6, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/dss/dsshome1/0A/ru56sax2/.local/lib/python3.8/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/dss/dsshome1/0A/ru56sax2/.local/lib/python3.8/site-packages/torchvision/datasets/_optical_flow.py", line 10, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 89, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
`

I followed exactly the steps described [here](https://github.com/mosaicml/examples/tree/main/examples/benchmarks/bert). As I work with the compute cluster of our university, I first had to create an enroot container from the docker image _mosaicml/pytorch:1.13.1_cu117-python3.10-ubuntu20.04_. Within that container, I cloned the examples repository, used 

> pip install -r requirements.txt

etc. The steps to convert the data to the .mds format and teh dataloader test worked well. However, the pre-training test failed. DO you have an idea what I do wrong?

**Comment by FinTexIFB** [comment]
I solved the problem now, I had some composer package outside the container which lead to some conflicts. Now everything is fine. Sorry for the confusion and thank's again for your help!

**Comment by FinTexIFB** [comment]
I solved the problem now, I had some composer package outside the container which lead to some conflicts. Now everything is fine. Sorry for the confusion and thank's again for your help!
